config/routes.rb
Rails.application.routes.draw do
  root "staticpages#home"
  get "about" => "staticpages#about"
  get "contact" => "staticpages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users do
     member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :words, only: [:index]
  resources :courses, only: [:index, :show] do
    resources :lessons, except: [:index, :destroy, :edit]
  end

  namespace :admin do
    root "courses#index"
    resources :courses do
      resources :words
    end
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
    @feed_items = Activity.activities(current_user).
      paginate page: params[:page]
  end
end

app/views/staticpages/home.html.erb
<% provide title: t("home") %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= gravatar_for current_user %>
          <%= current_user.name %>
        </h1>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
    </aside>
    <div class="col-md-8">
      <div class="row">
        <div class="col-md-2">
          <%= link_to t("word_list"), words_path, class: "btn btn-primary btn-lg" %>
        </div>
        <div class="col-md-2">
          <%= link_to t("lesson"), courses_path, class: "btn btn-danger btn-lg" %>
        </div>
      </div>
      <h3> <%= t "activities" %> </h3>
      <%= render "shared/feed" %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1><%= t "welcome" %></h1>
    <%= link_to t("signup"), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>